{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '0.0.2', 'tethys_version': '>=4.0.0', 'description': 'Ground Water Data Mapper', 'long_description': '', 'author': 'Sarva Pulla', 'author_email': '', 'url': 'https://github.com/BYU-Hydroinformatics/gwdm', 'license': 'MIT', 'app_package': 'gwdm', 'dev_url': 'https://github.com/Aquaveo/gwdm'}"
  dev_url: {{ data.get('dev_url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: ''
  keywords: []
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - geopandas
  - scipy
  - statsmodels
  - rioxarray
  - geojson
  - simplejson
  - pandarallel
  - gstools
  - thredds_crawler
  - matplotlib
  - sphinx_rtd_theme
  - sphinx
  - sphinxcontrib-napoleon
source:
  path: ..
